{"uuid": "73ed0aa1-3dc1-4f36-bc6c-1b95c3d6dd2a", "children": ["38b8acf4-0a6e-42c6-8f16-c3a672bd9316"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\DELL\\PycharmProjects\\pytest_POM_framework\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\DELL\\PycharmProjects\\pytest_POM_framework\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\DELL\\PycharmProjects\\pytest_POM_framework\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\PycharmProjects\\pytest_POM_framework\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\PycharmProjects\\pytest_POM_framework\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\PycharmProjects\\pytest_POM_framework\\demowebshop\\Tests\\conftest.py\", line 6, in driver\n    driver = WebDriver()\n             ^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\PycharmProjects\\pytest_POM_framework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\DELL\\PycharmProjects\\pytest_POM_framework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 55, in __init__\n    self.service.start()\n  File \"C:\\Users\\DELL\\PycharmProjects\\pytest_POM_framework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 103, in start\n    if self.is_connectable():\n       ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\PycharmProjects\\pytest_POM_framework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 120, in is_connectable\n    return utils.is_connectable(self.port)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\PycharmProjects\\pytest_POM_framework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\socket.py\", line 857, in create_connection\n    exceptions.clear()  # raise only the last error\n    ^^^^^^^^^^^^^^^^^^\n"}, "start": 1725344951919, "stop": 1725344953727}], "start": 1725344951919, "stop": 1725344954278}